name: Parse to LST

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  parse-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Protoc & Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
          pip install protobuf

      - name: Compile Protobuf Schema
        run: protoc --python_out=. router.proto

      - name: Run Parser Script
        run: python parser.py

      - name: Deploy Clean Results to Test Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: lists          # Ветка назначения для результатов
          folder: parser-tmp        # Экшен возьмет ТОЛЬКО файлы из этой папки и положит в корень ветки test
          clean: true           # Полностью сотрет старый мусор на ветке test перед коммитом
          single-commit: true   # Держит историю ветки test чистой (всегда 1 коммит с актуальным результатом)
